name: Push Nuget Package to Azure Artifacts or GitHub Package Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
env:
  BUILD_CONFIGURATION: 'Release'                                                          # set this to the appropriate build configuration
  DOTNET_VERSION: '6.0.x'                                                                   # set this to the dot net version to use
  GITHUB_PACKAGE_REGISTRY_URL: https://nuget.pkg.github.com/colincmac/index.json   # set this to the registry url for your GitHub package registry

jobs:
  gpr-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: ${{ env.GITHUB_PACKAGE_REGISTRY_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Setup the .NET Core SDK with the appropriate auth token to access the GitHub Package Registry

    - run: dotnet build
      
    - name: Create the package
      run: dotnet pack --configuration '${{ env.BUILD_CONFIGURATION }}' Oink.Core.sln

    - name: Publish the package to GPR
      run: dotnet nuget push **/*.nupkg
